# Wiggumizer Configuration
# See: https://github.com/bradledford/wiggumizer#configuration

# Default AI provider
provider: claude

# Maximum iterations before stopping
maxIterations: 20

# Convergence threshold (0.0 to 1.0)
# Lower = more strict convergence detection
convergenceThreshold: 0.02

# Automatically commit changes after each iteration
autoCommit: false

# Context limits
context:
  maxSize: 100000  # Maximum context size in bytes (100KB)
  maxFiles: 50     # Maximum number of files to include

# File patterns
# Note: .gitignore is automatically respected
files:
  include:
    - "**/*"  # Include all files (filtered by default extensions)
    # Or specify exact patterns:
    # - "src/**/*.js"
    # - "src/**/*.ts"
    # - "*.md"
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "dist/**"
    - "build/**"
    - ".wiggumizer/**"
    - ".claude/**"
    - "docs/**"
    - "coverage/**"
    - "*.test.js"
    - "*.min.js"
    - "package-lock.json"
    - "yarn.lock"
    - "*.log"

# Retry configuration for API calls
retry:
  maxRetries: 3        # Maximum number of retries
  baseDelay: 1000      # Base delay in milliseconds (1 second)
  maxDelay: 30000      # Maximum delay in milliseconds (30 seconds)

# Rate limiting configuration
rateLimit:
  requestsPerMinute: 50    # Maximum requests per minute
  requestsPerHour: 1000    # Maximum requests per hour

# Provider-specific configuration
providers:
  claude:
    model: claude-opus-4-5-20251101
    maxTokens: 8192

  openai:
    model: gpt-5
    maxTokens: 8192
