# Wiggumizer Configuration
# See: https://github.com/bradledford/wiggumizer#configuration

# Default AI provider
provider: claude

# Maximum iterations before stopping
maxIterations: 20

# Convergence threshold (0.0 to 1.0)
# Lower = more strict convergence detection
convergenceThreshold: 0.02

# Automatically commit changes after each iteration
autoCommit: false

# Context limits
context:
  maxSize: 100000  # Maximum context size in bytes (100KB)
  maxFiles: 50     # Maximum number of files to include

# File patterns
# Note: .gitignore is automatically respected
files:
  include:
    - "**/*"  # Include all files (filtered by default extensions)
    # Or specify exact patterns:
    # - "src/**/*.js"
    # - "src/**/*.ts"
    # - "*.md"
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "dist/**"
    - "build/**"
    - ".wiggumizer/**"
    - ".claude/**"
    - "docs/**"
    - "coverage/**"
    - "*.test.js"
    - "*.min.js"
    - "package-lock.json"
    - "yarn.lock"
    - "*.log"

# Provider-specific configuration
providers:
  claude:
    model: claude-opus-4-5-20251101
    maxTokens: 8192

  openai:
    model: gpt-5
    maxTokens: 8192
